name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add components
        run: rustup component add clippy
      - name: Build
        run: cargo build --verbose
      - name: Linting
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --verbose
